### ISSUE TITLE
Getting error message which opening XDM "An older version of XDM is already running."

### ISSUE THREAD

**Issue by AbhijitMusale** [subhra74/xdm#127]
Getting error message which opening XDM "An older version of XDM is already running."
![XDM_Error](https://user-images.githubusercontent.com/64015699/79750314-5d94f980-832e-11ea-9615-f3b22b7399b6.JPG)

**Comment by Sourav2005** [comment]
Go to your system tray and close any instances of xdm that may be running. Then try reinstalling.

**Comment by sina-rostami** [comment]
I've the "An older version of XDM is already running." problem as well.

**Comment by sina-rostami** [comment]
I followed these steps:
+ kill all xdm processes.
+ remove `~/.xdman/downloads.txt` file.
+ run xdm again.

and it fixed.
note that all incomplete downloads will be removed!

**Comment by Marvin1932** [comment]
I have the same problem and need help solving it. 
Marvin1932

**Comment by Marvin1932** [comment]
Where can I find the ~/.xdman/downloads.txt file?

**Comment by patrickasafe** [comment]
> Where can I find the ~/.xdman/downloads.txt file?

the "~" in "~/.xdman/" is your home folder in Linux.
PS.: the "." (dot) before"xdman" means it's a hidden folder.

**Comment by Werve** [comment]
Recently I have been having this problem on Windows and only a reboot seems to work.
The log is this:
```
[ main ] loading...
[ main ] 11.0.6 10.0
[ main ] Loading config...
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
it
[ main ] Loading language it
[ main ] Context initialized
checking for app update
[ Thread-0 ] Context initialized
[ Thread-1 ] java.net.BindException: Address already in use: NET_Bind
        at java.base/java.net.PlainSocketImpl.bind0(Native Method)
        at java.base/java.net.PlainSocketImpl.socketBind(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.bind(Unknown Source)
        at java.base/java.net.ServerSocket.bind(Unknown Source)
        at java.base/java.net.ServerSocket.bind(Unknown Source)
        at xdman.monitoring.BrowserMonitor.run(BrowserMonitor.java:186)
        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-1 ] instance already runninng
[ Thread-0 ] manifest download response: 200
7.2.11 7.2.11
```
