### ISSUE TITLE
Can not reconstruct downloaded file

### ISSUE THREAD

**Issue by Shadow035** [subhra74/xdm#130]
Can not reconstruct downloaded file if the file name contains characters which are invalid for windows file system like "|","?",">" etc.

It shows "Failed to attempt/convert file parts ...... write protected" error message.

**To Reproduce**
Download video https://www.youtube.com/watch?v=oP2oGREukAE

**Expected behavior**
The easy workaround is to save as a different valid name. 
But please implement an auto-renaming that trims the invalid characters or replaces them with valid characters like "_".

**Comment by subhra74** [comment]
the provided url is working fine on my pc, can you generate the logs mentioned in
https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

**Comment by SS-035** [comment]
My bad, I was not directly downloading the video from YT by XDM, I was using [y2mate](http://dl188.y2mate.com/?file=M3R4SUNiN3JsOHJ6WWQ2a3NQS1Y5ZGlxVlZIOCtyZ0d1dlp4NGhFeEZhTUg4OTFrNCt1d2FPZE9PcklkeklicE9kZEg0VEhLYUp1bVB3S011SXcxQ1RiVzFKMW82WEtib3JFdmFadCtjU1RkanUyQ3N3NG4zVlBsTU5YZFFmNVFaSHQrbkZCaXh5N09pYVB5b0JydHAyaXZvZ2pSU2lrYTVuNVpHNktWbzdsUmgyVEtlL0txMEo4STVtdlU0SmhLNWZXY3BoWCsvT2R1aDhoNlRudDZjb1JJeTV2NTRQakZ0bE1Xa29BajEwS3ByT3l5RmFGZ1RKcktLQWgvRG5BR3p0M0tTUkEvNmhwUHJEaXV1S0kxdWlZTWFiQjgrbWVnOFAvc08yN05KcHFtR2NmVWZyNzd0ZE9rOGU4eQ%3D%3D).

Generating log is taking some time, stuck at "icon type: hdpi".

**Comment by SS-035** [comment]
Here is the log:
[ main ] loading...
[ main ] 11.0.6 10.0
[ main ] starting monitoring...
[ Thread-0 ] instance starting...
[ Thread-0 ] Init app
[ Thread-0 ] Loading fonts
[ Thread-0 ] Loading config...
[ Thread-0 ] Creating folders
en
[ Thread-0 ] Loading language en
[ Thread-0 ] Context initialized
[ Thread-0 ] instance started.
[ AWT-EventQueue-0 ] showing main window.
New session
New session
checking for app update
[ AWT-EventQueue-0 ] Dpi scale init: 1.0
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
[ AWT-EventQueue-0 ] List changed
icon type:hdpi
[ Thread-1 ] manifest download response: 200
7.2.10 7.2.10
[ AWT-EventQueue-0 ] loading metadata: 6350928c-295a-446a-9115-13063b57a2ff
[ AWT-EventQueue-0 ] normal download
[ AWT-EventQueue-0 ] Resuming
[ AWT-EventQueue-0 ] File opened 2b35c917-906e-4551-954c-6e094d8bd25c
[ AWT-EventQueue-0 ] id: 2b35c917-906e-4551-954c-6e094d8bd25c
length: 10100952
offset: 0
download: 10100952
[ AWT-EventQueue-0 ] File opened 741bc28e-dae0-4764-9e47-dd5e2c7dfe02
[ AWT-EventQueue-0 ] id: 741bc28e-dae0-4764-9e47-dd5e2c7dfe02
length: 10149828
offset: 30502144
download: 10149828
[ AWT-EventQueue-0 ] File opened 5bf4e3ca-931a-4559-af71-d5e3034a121f
[ AWT-EventQueue-0 ] id: 5bf4e3ca-931a-4559-af71-d5e3034a121f
length: 7672577
offset: 45753216
download: 7672577
[ AWT-EventQueue-0 ] File opened 37b4deb7-5a04-4c54-bb15-c856a4075fa6
[ AWT-EventQueue-0 ] id: 37b4deb7-5a04-4c54-bb15-c856a4075fa6
length: 7607929
offset: 15370730
download: 7607929
[ AWT-EventQueue-0 ] File opened 9e298f83-40c2-4729-9131-14261fa2d365
[ AWT-EventQueue-0 ] id: 9e298f83-40c2-4729-9131-14261fa2d365
length: 7578495
offset: 53425793
download: 7578495
[ AWT-EventQueue-0 ] File opened ffd44664-7e8f-4741-9f63-a9c65565e72e
[ AWT-EventQueue-0 ] id: ffd44664-7e8f-4741-9f63-a9c65565e72e
length: 7523485
offset: 22978659
download: 7523485
[ AWT-EventQueue-0 ] File opened dcf5f91b-4212-480c-bb44-9967171682e3
[ AWT-EventQueue-0 ] id: dcf5f91b-4212-480c-bb44-9967171682e3
length: 2151060
offset: 10100952
download: 2151060
[ AWT-EventQueue-0 ] File opened 3900cc62-072f-4a40-b543-f3f98f840b8a
[ AWT-EventQueue-0 ] id: 3900cc62-072f-4a40-b543-f3f98f840b8a
length: 2522395
offset: 41868320
download: 2522395
[ AWT-EventQueue-0 ] File opened e82b9dcb-0ec5-45f7-9d47-de74a3f0f9cb
[ AWT-EventQueue-0 ] id: e82b9dcb-0ec5-45f7-9d47-de74a3f0f9cb
length: 1563603
offset: 12825328
download: 1563603
[ AWT-EventQueue-0 ] File opened e78562af-04b5-4ce4-a247-8ff98872afee
[ AWT-EventQueue-0 ] id: e78562af-04b5-4ce4-a247-8ff98872afee
length: 997497
offset: 44390715
download: 997497
[ AWT-EventQueue-0 ] File opened 615a6bd6-0062-4e81-ad88-30c419ca0055
[ AWT-EventQueue-0 ] id: 615a6bd6-0062-4e81-ad88-30c419ca0055
length: 1216348
offset: 40651972
download: 1216348
[ AWT-EventQueue-0 ] File opened 8733f8d7-cc85-4dd6-87e2-563f6dd0b0c0
[ AWT-EventQueue-0 ] id: 8733f8d7-cc85-4dd6-87e2-563f6dd0b0c0
length: 719266
offset: 14388931
download: 719266
[ AWT-EventQueue-0 ] File opened 89760db3-0d6a-461e-b426-61366a5a6b1f
[ AWT-EventQueue-0 ] id: 89760db3-0d6a-461e-b426-61366a5a6b1f
length: 573316
offset: 12252012
download: 573316
[ AWT-EventQueue-0 ] File opened 0b93b762-cc3d-4315-a561-1000bbb680e3
[ AWT-EventQueue-0 ] id: 0b93b762-cc3d-4315-a561-1000bbb680e3
length: 202144
offset: 45388212
download: 202144
[ AWT-EventQueue-0 ] File opened d6e8bc50-4d99-4804-8d23-3ee42b4ad057
[ AWT-EventQueue-0 ] id: d6e8bc50-4d99-4804-8d23-3ee42b4ad057
length: 262533
offset: 15108197
download: 262533
[ AWT-EventQueue-0 ] File opened 7ae90ab1-9691-4122-a076-3c1422330e63
[ AWT-EventQueue-0 ] id: 7ae90ab1-9691-4122-a076-3c1422330e63
length: 162860
offset: 45590356
download: 162860
[ AWT-EventQueue-0 ] Restore success
[ AWT-EventQueue-0 ] List changed
[ Thread-4 ] checking for same named file on disk...
[ Thread-4 ] Updating file name- old: y2mate.com - BBC Earth 50 Top Natural History Moments | 50-41_oP2oGREukAE_144p.mp4 new: y2mate.com - BBC Earth 50 Top Natural History Moments | 50-41_oP2oGREukAE_144p.mp4
[ Thread-4 ] assembling...
[ Thread-4 ] java.io.FileNotFoundException: C:\Users\saika\Downloads\Videos\92807399-4f6e-42e8-ba99-49d2a70902ab_y2mate.com - BBC Earth 50 Top Natural History Moments | 50-41_oP2oGREukAE_144p.mp4 (The filename, directory name, or volume label syntax is incorrect)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at xdman.downloaders.SegmentDownloader.assemble(SegmentDownloader.java:318)
        at xdman.downloaders.SegmentDownloader$1.run(SegmentDownloader.java:598)
        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-4 ] java.io.IOException: java.io.FileNotFoundException: C:\Users\saika\Downloads\Videos\92807399-4f6e-42e8-ba99-49d2a70902ab_y2mate.com - BBC Earth 50 Top Natural History Moments | 50-41_oP2oGREukAE_144p.mp4 (The filename, directory name, or volume label syntax is incorrect)
        at xdman.downloaders.SegmentDownloader.assemble(SegmentDownloader.java:396)
        at xdman.downloaders.SegmentDownloader$1.run(SegmentDownloader.java:598)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Users\saika\Downloads\Videos\92807399-4f6e-42e8-ba99-49d2a70902ab_y2mate.com - BBC Earth 50 Top Natural History Moments | 50-41_oP2oGREukAE_144p.mp4 (The filename, directory name, or volume label syntax is incorrect)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at xdman.downloaders.SegmentDownloader.assemble(SegmentDownloader.java:318)
        ... 2 more
[ Thread-4 ] List updated
[ Thread-4 ] removed
[ Thread-3 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.java:498)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:527)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by subhra74** [comment]
ok, i will analyze it. just curious though: why not use XDM itself for detecting and downloading the video

**Comment by SS-035** [comment]
In that website, I can see download sizes of all formats including mp3s and then I download whatever I need using XDM.
