### ISSUE TITLE
XDM hangs if I try to delete files from download queue

### ISSUE THREAD

**Issue by nick51** [subhra74/xdm#166]
I added three YouTube URLs manually, via Download Video. These were added to queue that was supposed to run at midnight. When I checked the queue just after midnight, the status was switching rapidly between 'Downloading' and 'Paused'. Now I can see three entries in the default queue under tab 'Incomplete'. The entries are shown as 'Paused'. If I Right-Click and select 'Delete downloads' and click 'Yes' on the 'Delete Confirmation' screen, XDM hangs. The only way to exit the programme is via Task Manager. If I click 'Downloads' and then 'Queue and Scheduler' there are no filenames listed as 'Files in queue'. 

When trying to end process via Task manager, I get a message saying that the OpenJDK Platform binary is not responding:

![Capture](https://user-images.githubusercontent.com/25934263/81904602-c7b65c80-95c3-11ea-97c5-7e225e35d724.PNG)

XDM version = xdmsetup_7.2.10
Java = Version 8 update 251
OS = Windows 7 Home Premium
Browser = Google Chrome Version 81.0.4044.138 (Official Build) (32-bit)

I have uninstalled and reinstalled XDM three times, once with a previous version (2018), but every time the three entries reappear under 'Incomplete' and the system hangs if I try to delete them.

**Generated log using below method**
 - https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

I followed those instructions, and this was the output:

////////////////////////////////////////////
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\nick>cd "C:\Program Files\XDM"

C:\Program Files\XDM> "java-runtime\bin\java" -jar xdman.jar
[ main ] loading...
[ main ] 11.0.6 6.1
[ main ] starting monitoring...
[ Thread-0 ] java.net.BindException: Address already in use: NET_Bind
        at java.base/java.net.PlainSocketImpl.bind0(Native Method)
        at java.base/java.net.PlainSocketImpl.socketBind(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.bind(Unknown Source)
        at java.base/java.net.ServerSocket.bind(Unknown Source)
        at java.base/java.net.ServerSocket.bind(Unknown Source)
        at xdman.monitoring.BrowserMonitor.run(BrowserMonitor.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-0 ] instance already runninng

C:\Program Files\XDM>
////////////////////////////////////////////

I hope you can assist. Thanks.

**Comment by subhra74** [comment]
Please perform below steps:
1. Go to XDM menu->Downloads->Stop Queue
![image](https://user-images.githubusercontent.com/8403090/81972488-f283cd80-9622-11ea-951c-b0ff0c0eae50.png)
2. Stop the queue if it is present.
3. Now delete the files
