### ISSUE TITLE
XDM prevents loading Sketchfab models

### ISSUE THREAD

**Issue by L0Lock** [subhra74/xdm#167]
**Describe the bug**
When browsing on sketchfab with XDM extension ON, it is impossible to load and see any model on the site as XDM will try to download  something which will prevent Sketchfab to work properly.

**To Reproduce**
1. Go to https://sketchfab.com/feed
2. Click any model in order to watch it
3. XDM will show up with a download
4. Accept the download or cancel it, doesn't matter
5. Model's loading is forever stuck
![2020-05-15_11-31-23](https://user-images.githubusercontent.com/16049822/82036723-885e3d80-96a1-11ea-9a9b-a2f8f4921117.gif)

**Expected behavior**
On step 3, XDM shouldn't show up, the "Loading 3D Model" should just keep loading and then disapear to show the model.
![demo_XDM_bug](https://user-images.githubusercontent.com/16049822/82036755-94e29600-96a1-11ea-9cf4-3e77ea3cf2f5.gif)

**please complete the following information:**
 - OS: Windows 10
 - Browser: Firefox 76.0.1
 - XDM addon Version 2.1
 - XDM Version 7.2.10

**Generated log**
```batch
Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\XDM>"java-runtime\bin\java" -jar xdman.jar
[ main ] loading...
[ main ] 11.0.6 10.0
[ main ] starting monitoring...
[ Thread-0 ] instance starting...
[ Thread-0 ] Init app
[ Thread-0 ] Loading fonts
[ Thread-0 ] Loading config...
[ Thread-0 ] Creating folders
en
[ Thread-0 ] Loading language en
[ Thread-0 ] Context initialized
[ Thread-0 ] instance started.
[ AWT-EventQueue-0 ] showing main window.
New session
New session
[ AWT-EventQueue-0 ] Dpi scale init: 1.0
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
icon type:hdpi
[ AWT-EventQueue-0 ] List changed
icon type:hdpi
checking for app update
[ Thread-1 ] manifest download response: 200
7.2.10 7.2.10
[ Thread-3 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.java:498)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:527)
        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-2 ] url=https://media.sketchfab.com/models/5c81c196c8cd43cf9f53064ba611d449/4aad727467df4a6f869f6958883a66b6/files/74193d7629da44578ba749ac1a692195/model_file.bin.gz
file=/models/5c81c196c8cd43cf9f53064ba611d449/4aad727467df4a6f869f6958883a66b6/files/74193d7629da44578ba749ac1a692195/model_file.bin.gz
req=Host:media.sketchfab.com
req=User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
req=Accept:*/*
req=Accept-Language:en-US,en;q=0.7,fr-FR;q=0.3
req=Accept-Encoding:gzip, deflate, br
req=Referer:https://sketchfab.com/3d-models/xylia-daughter-of-the-red-moon-5c81c196c8cd43cf9f53064ba611d449
req=Origin:https://sketchfab.com
req=Connection:keep-alive
res=content-type:text/plain
res=content-length:2402531
res=date:Fri, 15 May 2020 09:29:28 GMT
res=access-control-allow-origin:*
res=access-control-allow-methods:GET, HEAD
res=access-control-max-age:3000
res=last-modified:Thu, 17 Oct 2019 19:19:06 GMT
res=etag:"b81ddf035a556d7c1bf253c08d9ce41b"
res=x-amz-storage-class:STANDARD_IA
res=content-encoding:gzip
res=x-amz-version-id:naXBQ271Lr12Nu2BgbWfZI6lZcbRaAu5
res=accept-ranges:bytes
res=server:AmazonS3
res=vary:Origin
res=x-cache:Miss from cloudfront
res=via:1.1 a7dcca466407f1871feceef50bc84272.cloudfront.net (CloudFront)
res=x-amz-cf-pop:FRA6-C1
res=x-amz-cf-id:4F0-K5eXcjwRoQdpyR45wg6_KgMBxDunEBHVq89kOQxG_FCVKCkw-w==
res=X-Firefox-Spdy:h2
res=Content-Security-Policy:upgrade-insecure-requests
res=tabId:-1
res=realUA:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0

New session
req=Host:media.sketchfab.com
req=User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
req=Accept:*/*
req=Accept-Language:en-US,en;q=0.7,fr-FR;q=0.3
[ Thread-4 ] sending 204...
req=Accept-Encoding:gzip, deflate, br
req=Referer:https://sketchfab.com/3d-models/xylia-daughter-of-the-red-moon-5c81c196c8cd43cf9f53064ba611d449
req=Origin:https://sketchfab.com
req=Connection:keep-alive
icon type:hdpi
icon type:hdpi
``

**Comment by subhra74** [comment]
You can set exception for certain url:
![image](https://user-images.githubusercontent.com/8403090/82142729-ad3be780-983e-11ea-86cd-30da63f7c9cc.png)

**Comment by L0Lock** [comment]
Indeed, thank you :o

Sorry for the bother.
