### ISSUE TITLE
"Download failed. Failed to append/convert file parts, please check if the drive is full or write protected"

### ISSUE THREAD

**Issue by Ormendahl** [subhra74/xdm#192]
**Describe the bug**To Reproduce**
Everytime i try to download a video from tubi i get this error after it reaches 100% downloaded. It still occupies the total file space it took to donwload in the temp folder but it just doesn't convert to get the single video file.

**To Reproduce**
Any video on tubi. Maybe it's a known bug that happens with other sites or this site it isn't supposed to be supported i don't know, but the thing is that it download the full size of the file itself it just can't append it/convert it.

 - OS: [Windows]
 - Browser [Chrome]
 - XDM addon Version [e.g. 2.0]
 - XDM Version [e.g. 7.2.11]

**Generated log""

[ main ] loading...
[ main ] 11.0.6 6.1
[ main ] Loading config...
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
en
[ main ] Loading language en
[ main ] Context initialized
checking for app update
[ Thread-0 ] Context initialized
[ Thread-1 ] instance starting...
[ Thread-1 ] instance started.
[ Thread-1 ] Lock acquired...
[ AWT-EventQueue-0 ] showing main window.
Loading image from url: jar:file:/C:/Program%20Files%20(x86)/XDM/xdman.jar!/icon
s/xxhdpi/icon.png
Loading image from url: jar:file:/C:/Program%20Files%20(x86)/XDM/xdman.jar!/icon
s/xxhdpi/icon.png
Error setting Dock icon
Loading image from url: jar:file:/C:/Program%20Files%20(x86)/XDM/xdman.jar!/icon
s/xxhdpi/bg_nav.png
[ Thread-0 ] manifest download response: 200
7.2.11 7.2.11
[ AWT-EventQueue-0 ] List changed
Loading image from url: jar:file:/C:/Program%20Files%20(x86)/XDM/xdman.jar!/icon
s/xxhdpi/icon.png
New session
[ Thread-2 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
New session
[ Thread-3 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
New session
[ Thread-4 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
New session
[ Thread-5 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
New session
[ Thread-6 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
New session
[ AWT-EventQueue-0 ] Max download: 100
[ AWT-EventQueue-0 ] Category changed
[ Thread-7 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
New session
[ Thread-8 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
New session
[ Thread-9 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
New session
[ Thread-10 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
New session

**Comment by roba953** [comment]
I have a similar issue on my laptop and my tablet since I installed the newest version.

**Comment by roba953** [comment]
I uninstalled version 7.2.11 and re-installed version 7.2.10.  I was able to resume downloads.

**Comment by bahramdolati** [comment]
I have the same problem after installing version 7.2.11. I uninstalled this version completely and deleted all related files (i.e /opt/xdman and ~/.xdman/) then I installed 7.2.10 version but encountered the same problem. Xdm was working perfectly before any of this. It seems It has a problem with writing privileges. Because when I run it under sudo and root, it works without any problem (Of course in this scenario it saves files into /root/Downloads). But when I run it under standard user, It gives an error that says it can't append/convert.
Besides that, I am don't have storage problems definitely. Because the file I am downloading is 4MB and I have 87GB free space on my drive.
Also, I am running Ubuntu 20.04.

**Comment by jchampeau** [comment]
I've had the same problem with 7.2.11.  As suggested in a previous post, I switched back to 7.2.10 and it started working.  This is on Windows 8.

**Comment by buddudevelopers** [comment]
Same issue with 7.2.11 when downloading large videos from xvideos :) The issue occurs sporadically and is hard to reproduce but has happened twice. Again downgrading to 7.2.10 solves the issue

**Comment by Ormendahl** [comment]
[This solution]https://github.com/subhra74/xdm/issues/198#issuecomment-635621796(url) fixed my problem.

**Comment by kpilkk** [comment]
I had the same problem. I renamed my file as the name was too long and this solved my problem.

**Comment by Aikatsui** [comment]
https://github.com/subhra74/xdm/issues/272

**Comment by mustious** [comment]
try shortening the filename using "Save As" then "Resume" download. It works

**Comment by tikendraw** [comment]
> I uninstalled version 7.2.11 and re-installed version 7.2.10. I was able to resume downloads.

Did it deleted all this unfinished data? Or not? / Do I have to download it again?

**Comment by Overlrd** [comment]
same problem, i'm on Ubuntu 22.04.
I switch to version 10.2.10 but the issue persist

**Comment by Overlrd** [comment]
Ubuntu 22.04
Firefox
XDM 10.2.10

I notice that this error occures when i change the name of the file in the download panel.

![image](https://user-images.githubusercontent.com/90383672/208074397-7f8c2e4a-25b2-435d-a519-48cf93f51b42.png)

**Comment by imbiss** [comment]
I had the same problem when upgrading to Ubuntu 24. By looking at xdm's log, I found that it depends on ffmpeg when merging video files in the last one. but the ffmpeg that comes with xdm doesn't work on the new system because the public library file libvpx.so.6 that ffmpeg depends on is removed.

My solution
1. install ffmpeg independently on the new system. usually it will be installed in /usr/bin/ffmpeg 
2. Replace the ffmpeg that comes with xdm with the newly installed ffmpeg binary. 

That's it.

**Comment by Bantamlak12** [comment]
I had the same issue. Whenever I tried to resume the download, the following message kept popping up:

`Failed to append/convert file parts, please check if the drive is full or write protected`

This happened on Ubuntu 24.04 with XDM version 7.2.11.

The issue was not related to disk space or permissions. The problem was that XDM uses its bundled **ffmpeg** to merge/convert video files after downloading. The ffmpeg version included with XDM was built for older Ubuntu versions and depends on libraries that are no longer available in Ubuntu 24.04 (for example, `libvpx.so.6`).

The fix is to install Ubuntu's latest ffmpeg and make XDM use it instead of the outdated bundled version.

## Steps to fix

```bash
sudo apt update
sudo apt install ffmpeg
````

Verify that it was installed correctly:

```bash
ffmpeg -version
```

---

### 2. Locate XDM's bundled ffmpeg

Find the `ffmpeg` binary included with XDM:

```bash
find / -name ffmpeg 2>/dev/null | grep -i xdm
```

For most installations, XDM is located at:

```bash
/opt/xdman/
```

and the bundled ffmpeg file will be:

```bash
/opt/xdman/ffmpeg
```

---

### 3. Backup XDM's original ffmpeg

Rename the old XDM ffmpeg file:

```bash
sudo mv /opt/xdman/ffmpeg /opt/xdman/ffmpeg.old
```

This keeps a backup in case you need to restore it later.

---

### 4. Create a symbolic link to Ubuntu's ffmpeg

Create a link so XDM uses the system ffmpeg:

```bash
sudo ln -s /usr/bin/ffmpeg /opt/xdman/ffmpeg
```

Confirm that the link was created:

```bash
ls -l /opt/xdman/ffmpeg
```

Expected output:

```text
ffmpeg -> /usr/bin/ffmpeg
```

---

### 5. Restart XDM
