### ISSUE TITLE
Weird UI in Arch/Manjaro linux (The UI is broken)

### ISSUE THREAD

**Issue by abedih** [subhra74/xdm#207]
Hi
I updated the XDM to the latest version. but the UI became completely useless. I used both the AUR package and the stand alone package from here. I've attached the screenshot.. my system:

OS: Linux Manjaro (updated to the latest version)
DE: KDE
Monitor resolution: 4k (HiDPI)
java version: openjdk version "13.0.2" 2020-01-14

Logs (when I run xdm from terminal):
`[ main ] loading...
[ main ] 13.0.2 5.6.12-1-MANJARO
[ main ] Loading config...
[ main ] Creating folders
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
[ main ] java.lang.NullPointerException: Unexpected EOF
        at xdman.XDMApp.loadDownloadList(XDMApp.java:811)
        at xdman.XDMApp.loadDownloadList(XDMApp.java:795)
        at xdman.XDMApp.<init>(XDMApp.java:235)
        at xdman.XDMApp.getInstance(XDMApp.java:384)
        at xdman.monitoring.BrowserMonitor.getSync(BrowserMonitor.java:119)
        at xdman.monitoring.BrowserMonitor.updateSettingsAndStatus(BrowserMonitor.java:48)
        at xdman.monitoring.BrowserMonitor.startMonitoring(BrowserMonitor.java:37)
        at xdman.XDMApp.start(XDMApp.java:201)
        at xdman.Main.main(Main.java:25)
en
[ main ] Loading language en
[ main ] Context initialized
[ Thread-1 ] java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:469)
        at java.base/sun.nio.ch.Net.bind(Net.java:458)
        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:374)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:328)
        at xdman.monitoring.BrowserMonitor.run(BrowserMonitor.java:186)
        at java.base/java.lang.Thread.run(Thread.java:830)
[ Thread-1 ] instance already runninng
`
![xdm-1](https://user-images.githubusercontent.com/18257531/83321403-b37d8b00-a264-11ea-9805-8673cd11ecfa.png)

**Comment by subhra74** [comment]
please follow steps mentioned in:
https://github.com/subhra74/xdm/issues/44#issuecomment-601229415

**Comment by abedih** [comment]
Thanks @subhra74 
but it didn't work. I tried it several  times but the UI did not fix

**Comment by subhra74** [comment]
Please post the log again. If you performed the suggested steps properly then below error should not appear in log
`java.net.BindException: Address already in use at`

**Comment by abedih** [comment]
@subhra74 

this is the log from termial:

`[ main ] loading...
[ main ] 11.0.6 5.6.12-1-MANJARO
[ main ] Loading config...
[ main ] Creating folders
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
[ main ] java.lang.NullPointerException: Unexpected EOF
        at xdman.XDMApp.loadDownloadList(XDMApp.java:811)
        at xdman.XDMApp.loadDownloadList(XDMApp.java:795)
        at xdman.XDMApp.<init>(XDMApp.java:235)
        at xdman.XDMApp.getInstance(XDMApp.java:384)
        at xdman.monitoring.BrowserMonitor.getSync(BrowserMonitor.java:119)
        at xdman.monitoring.BrowserMonitor.updateSettingsAndStatus(BrowserMonitor.java:48)
        at xdman.monitoring.BrowserMonitor.startMonitoring(BrowserMonitor.java:37)
        at xdman.XDMApp.start(XDMApp.java:201)
        at xdman.Main.main(Main.java:25)
en
[ main ] Loading language en
[ main ] Context initialized
[ Thread-4 ] instance starting...
[ Thread-4 ] instance started.
[ Thread-4 ] Lock acquired...
[ AWT-EventQueue-0 ] showing main window.
Loading image from url: jar:file:/opt/xdman/xdman.jar!/icons/xxhdpi/icon.png
Error setting Dock icon
checking for app update
Loading image from url: jar:file:/opt/xdman/xdman.jar!/icons/xxhdpi/bg_nav.png
[ AWT-EventQueue-0 ] List changed
[ Thread-3 ] manifest download response: 200
7.2.11 7.2.11
`

**Comment by subhra74** [comment]
From the log it looks like the download list has been corrupted. 
First kill  xdman using `ps- ef|grep xdman` to get current XDM process and use `kill -9 <PID>` to kill that process. 
Then remove the `$HOME/.xdman` directory. (Warning: it will clear download history).

**Comment by abedih** [comment]
@subhra74 
sorry for the delay
I've done that but without any success. also today I installed xdm on a fresh installation of Manjaro (using AUR) and it was the same.
![Screenshot_20200607_233755](https://user-images.githubusercontent.com/18257531/83971761-487e2500-a8f2-11ea-8c73-5d2f14c107b6.png)


is it because of my Java version? I'm using openjdk-jre version 14
