### ISSUE TITLE
Address already in use: NET_Bind

### ISSUE THREAD

**Issue by ashu9415** [subhra74/xdm#305]
while trying to run on eclipse on java 11
acing this issue

[ main ] Context initialized
[ Thread-1 ] java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.PlainSocketImpl.bind0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:132)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:335)
	at xdman.monitoring.BrowserMonitor.run(BrowserMonitor.java:186)
	at java.base/java.lang.Thread.run(Thread.java:834)
[ Thread-1 ] instance already runninng

**Comment by subhra74** [comment]
You need to kill/quit running instance of XDM
