### ISSUE TITLE
does not run on manjaro linux

### ISSUE THREAD

**Issue by zany130** [subhra74/xdm#34]
**Describe the bug**
does not run on manjaro linux fails with a java error
**To Reproduce**
1. install
2. run in terminal
3. See error

**Expected behavior**
no error shown

**Screenshots**
```
 xdman 
[ main ] loading...
[ main ] 13.0.1 5.4.12-ck1-23-tkg-MuQSS
[ main ] starting monitoring...
[ Thread-0 ] instance starting...
[ Thread-0 ] Init app
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-13-openjdk/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
        at java.base/java.lang.Runtime.load0(Runtime.java:744)
        at java.base/java.lang.System.load(System.java:1873)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2440)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2497)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:806)
        at java.base/java.lang.System.loadLibrary(System.java:1909)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1380)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1378)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1377)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1410)
        at java.desktop/java.awt.Color.<clinit>(Color.java:275)
        at java.desktop/javax.swing.plaf.metal.MetalTheme.<clinit>(MetalTheme.java:76)
        at xdman.ui.laf.XDMLookAndFeel.<init>(XDMLookAndFeel.java:14)
        at xdman.XDMApp.<init>(XDMApp.java:197)
        at xdman.XDMApp.getInstance(XDMApp.java:354)
        at xdman.XDMApp.instanceStarted(XDMApp.java:93)
        at xdman.monitoring.BrowserMonitor.run(BrowserMonitor.java:31)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Vivaldi
 - Version 2.10.1745.27 (Stable channel) (64-bit)

**Comment by S8D** [comment]
"An older version of XDM is already running"
How to update XDM?

**Comment by ask1234560** [comment]
sudo yay -S xdman
