### ISSUE TITLE
Connecting to: http://xdman.sourceforge.net/components/mac.zip null

### ISSUE THREAD

**Issue by gschen** [subhra74/xdm#38]
![image](https://user-images.githubusercontent.com/839140/74927170-18c61280-5412-11ea-8ea0-875e736ec015.png)
![image](https://user-images.githubusercontent.com/839140/74927188-1ebbf380-5412-11ea-9b54-1868d447ac9b.png)

```
[ cc51904a-a7b8-4bc1-886e-4c5f12b5bb4f ] Sending request:
GET /components/mac.zip HTTP/1.1
Range: bytes=0-
host: xdman.sourceforge.net


java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.net.SocketInputStream.read(SocketInputStream.java:224)
        at xdman.util.NetUtils.readLine(NetUtils.java:16)
        at xdman.network.http.XDMHttpClient.connect(XDMHttpClient.java:90)
        at xdman.downloaders.http.HttpChannel.connectImpl(HttpChannel.java:123)
        at xdman.downloaders.AbstractChannel.connect(AbstractChannel.java:44)
        at xdman.downloaders.AbstractChannel.run(AbstractChannel.java:61)
        at java.lang.Thread.run(Thread.java:748)
[ cc51904a-a7b8-4bc1-886e-4c5f12b5bb4f ] cc51904a-a7b8-4bc1-886e-4c5f12b5bb4f
[ cc51904a-a7b8-4bc1-886e-4c5f12b5bb4f ] xdman.network.NetworkException: Connection reset
        at xdman.network.http.XDMHttpClient.connect(XDMHttpClient.java:126)
        at xdman.downloaders.http.HttpChannel.connectImpl(HttpChannel.java:123)
        at xdman.downloaders.AbstractChannel.connect(AbstractChannel.java:44)
        at xdman.downloaders.AbstractChannel.run(AbstractChannel.java:61)
        at java.lang.Thread.run(Thread.java:748)
[ cc51904a-a7b8-4bc1-886e-4c5f12b5bb4f ] Connecting to: http://xdman.sourceforge.net/components/mac.zip null
```

**Comment by srbala** [comment]
Still same issue on Mac is this working for anyone?
