### ISSUE TITLE
Download from clipboard freezes XDM and prevents it from opening afterwards, if you had a lot of links in clipboard (I had 661 link)

### ISSUE THREAD

**Issue by NKSHV** [subhra74/xdm#426]
**Describe the bug**
XDM freezes and won't open afterwards if download from clipboard included too many files (about 600)

**To Reproduce**
I had a list of 661 links in clipboard
Open download from clipboard in XDM
Start the download
XDM freezes, and if you kill it, it won't open afterwards

**Expected behavior**
XDM downloads 661 files

**please complete the following information:**
 - OS: Windows 10 Home x64
 - XDM Version: 7.2.11

**Generated log using below method**
 - https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting
```
C:\Program Files (x86)\XDM>"java-runtime\bin\java" -jar xdman.jar
[ main ] loading...
[ main ] 11.0.6 10.0
[ main ] Loading config...
[ main ] Creating folders
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
en
[ main ] Loading language en
[ main ] Context initialized
[ Thread-1 ] instance starting...
[ Thread-1 ] instance started.
[ AWT-EventQueue-0 ] showing main window.
[ Thread-1 ] Lock acquired...
Loading image from url: jar:file:/C:/Program%20Files%20(x86)/XDM/xdman.jar!/icons/xxhdpi/icon.png
New session
Loading image from url: jar:file:/C:/Program%20Files%20(x86)/XDM/xdman.jar!/icons/xxhdpi/icon.png
Error setting Dock icon
Loading image from url: jar:file:/C:/Program%20Files%20(x86)/XDM/xdman.jar!/icons/xxhdpi/bg_nav.png
[ AWT-EventQueue-0 ] List changed
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.base/java.util.TimSort.mergeLo(Unknown Source)
        at java.base/java.util.TimSort.mergeAt(Unknown Source)
        at java.base/java.util.TimSort.mergeCollapse(Unknown Source)
        at java.base/java.util.TimSort.sort(Unknown Source)
        at java.base/java.util.Arrays.sort(Unknown Source)
        at java.base/java.util.ArrayList.sort(Unknown Source)
        at java.base/java.util.Collections.sort(Unknown Source)
        at xdman.ui.components.DownloadTableModel.sort(DownloadTableModel.java:68)
        at xdman.ui.components.DownloadTableModel.listChanged(DownloadTableModel.java:50)
        at xdman.ui.components.DownloadListView.refresh(DownloadListView.java:71)
        at xdman.ui.components.MainWindow.filter(MainWindow.java:374)
        at xdman.ui.components.MainWindow.initWindow(MainWindow.java:957)
        at xdman.ui.components.MainWindow.<init>(MainWindow.java:102)
        at xdman.XDMApp.showMainWindow(XDMApp.java:206)
        at xdman.XDMApp$1.run(XDMApp.java:112)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
New session
checking for app update
[ Thread-0 ] manifest download response: 200
7.2.11 7.2.11
[ Thread-3 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.java:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by NKSHV** [comment]
With additional testing, sometimes it can handle 1000+ links and sometimes it breaks at 200 links, that is completely random
