### ISSUE TITLE
Cannot Download any YouTube videos (via Find)

### ISSUE THREAD

**Issue by ValeTheVioletMote** [subhra74/xdm#442]
Attempting to find a YouTube video via File->Download Video->Find no longer works. I have tried this on both Windows and Linux, with all of three of the released versions, with both the "native" and the java. I have tried this in multiple networks.

```
[ Thread-6 ] /opt/xdman/youtube-dl
[ Thread-6 ] --no-warnings
[ Thread-6 ] -q
[ Thread-6 ] -i
[ Thread-6 ] -J
[ Thread-6 ] https://www.youtube.com/watch?v=D-iZddFKqiI
[ Thread-6 ] Writing JSON to: /home/vale/.xdman/temp/3e4e5089-fae5-4819-985f-35678bd0735b
[ Thread-6 ] Unexpected token END OF FILE at position 0.
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
	at xdman.videoparser.YdlResponse.parse(YdlResponse.java:27)
	at xdman.videoparser.YoutubeDLHandler.start(YoutubeDLHandler.java:123)
	at xdman.ui.components.MediaDownloaderWnd$2.run(MediaDownloaderWnd.java:480)

```

**Comment by ValeTheVioletMote** [comment]
More errors popped up:

```
Loading image from url: jar:file:/opt/xdman/xdman.jar!/icons/xxhdpi/icon.png
[ Thread-6 ] /opt/xdman/youtube-dl
[ Thread-6 ] --no-warnings
[ Thread-6 ] -q
[ Thread-6 ] -i
[ Thread-6 ] -J
[ Thread-6 ] https://www.youtube.com/watch?v=D-iZddFKqiI
[ Thread-6 ] Writing JSON to: /home/vale/.xdman/temp/3e4e5089-fae5-4819-985f-35678bd0735b
[ Thread-6 ] Unexpected token END OF FILE at position 0.
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
	at xdman.videoparser.YdlResponse.parse(YdlResponse.java:27)
	at xdman.videoparser.YoutubeDLHandler.start(YoutubeDLHandler.java:123)
	at xdman.ui.components.MediaDownloaderWnd$2.run(MediaDownloaderWnd.java:480)
[ AWT-EventQueue-0 ] Total video found: 0
Loading image from url: jar:file:/opt/xdman/xdman.jar!/icons/xxhdpi/icon.png
[ AWT-EventQueue-0 ] java.net.MalformedURLException: no protocol: [ Thread-6 ] /opt/xdman/youtube-dl
[ Thread-6 ] --no-warnings
[ Thread-6 ] -q
[ Thread-6 ] -i
[ Thread-6 ] -J
[ Thread-6 ] https://www.youtube.com/watch?v=D-iZddFKqiI
[ Thread-6 ] Writing JSON to: /home/vale/.xdman/temp/3e4e5089-fae5-4819-985f-35678bd0735b
[ Thread-6 ] Unexpected token END OF FILE at position 0.
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
	at xdman.videoparser.YdlResponse.parse(YdlResponse.java:27)
	at xdman.videoparser.YoutubeDLHandler.start(YoutubeDLHandler.java:123)
	at xdman.ui.components.MediaDownloaderWnd$2.run(MediaDownloaderWnd.java:480)

	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at xdman.ui.components.MediaDownloaderWnd.<init>(MediaDownloaderWnd.java:94)
	at xdman.ui.components.MainWindow.showVideoDwnDlg(MainWindow.java:1251)
	at xdman.ui.components.MainWindow.actionPerformed(MainWindow.java:312)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Loading image from url: jar:file:/opt/xdman/xdman.jar!/icons/xxhdpi/icon.png
[ AWT-EventQueue-0 ] java.net.MalformedURLException: no protocol: [ Thread-6 ] /opt/xdman/youtube-dl
[ Thread-6 ] --no-warnings
[ Thread-6 ] -q
[ Thread-6 ] -i
[ Thread-6 ] -J
[ Thread-6 ] https://www.youtube.com/watch?v=D-iZddFKqiI
[ Thread-6 ] Writing JSON to: /home/vale/.xdman/temp/3e4e5089-fae5-4819-985f-35678bd0735b
[ Thread-6 ] Unexpected token END OF FILE at position 0.
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
	at xdman.videoparser.YdlResponse.parse(YdlResponse.java:27)
	at xdman.videoparser.YoutubeDLHandler.start(YoutubeDLHandler.java:123)
	at xdman.ui.components.MediaDownloaderWnd$2.run(MediaDownloaderWnd.java:480)

	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at xdman.ui.components.MediaDownloaderWnd.<init>(MediaDownloaderWnd.java:94)
	at xdman.ui.components.MainWindow.showVideoDwnDlg(MainWindow.java:1251)
	at xdman.ui.components.MainWindow.actionPerformed(MainWindow.java:312)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by ValeTheVioletMote** [comment]
Notably, if I use the XDM extension on my browser, I get some offerings and can download, but they're low quality offerings (360p).

**Comment by ValeTheVioletMote** [comment]
Solution was to run, at least on linux, `sudo /opt/xdman/youtube-dl --update`
