### ISSUE TITLE
Why are 7.2.11 and 7.2.10 portable java versions not working?

### ISSUE THREAD

**Issue by KindlyOnes** [subhra74/xdm#467]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I had no problem with the portable java 7.2.8 version. It just wants me to update it when I'm on the program. Nobody has reported this before. Can you tell me how I can make it work?

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: xdman/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

Regards. :)

**Comment by Jmunsey859** [comment]
I'm having the same issue as well, are you on a arch based system? I am on Garuda Blackarch-edition.

**Comment by dickyharper** [comment]
> 
> 
> I'm having the same issue as well, are you on a arch based system? I am on Garuda Blackarch-edition.

I've tried in LinuxMint and Windows10. The result was the same. I'm now using the installer version in both.
