### ISSUE TITLE
No UI in v 7.2.11

### ISSUE THREAD

**Issue by Xan-Kerem** [subhra74/xdm#492]
After installing the version 7.2.11 on PopOs latest version when I wanna open XDM there is nothing to show.
It doesn't show any main screen of XDM for resume or to see list of previous download list.
But actually I can use it for download(witout being able to see and use main screen of software). When for  2nd time I run XDM it says " An older version of XDM is already running "!!!

**Comment by mohamed-khadragy** [comment]
I have the same problem. and it seems to be a java problem.
I tried to run the app as root and the UI loaded successfully. but when run it normally, it gives me this error

```
[ main ] loading...
[ main ] 11.0.6 5.8.0-45-generic
[ main ] Loading config...
[ main ] Creating folders
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
en
[ main ] Loading language en
[ main ] Context initialized
[ Thread-4 ] instance starting...
[ Thread-4 ] instance started.
[ AWT-EventQueue-0 ] showing main window.
[ Thread-4 ] Lock acquired...
Loading image from url: jar:file:/opt/xdman/xdman.jar!/icons/xxhdpi/icon.png
Error setting Dock icon
Loading image from url: jar:file:/opt/xdman/xdman.jar!/icons/xxhdpi/bg_nav.png
[ AWT-EventQueue-0 ] List changed
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(Unknown Source)
	at java.base/java.util.TimSort.mergeAt(Unknown Source)
	at java.base/java.util.TimSort.mergeCollapse(Unknown Source)
	at java.base/java.util.TimSort.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at java.base/java.util.ArrayList.sort(Unknown Source)
	at java.base/java.util.Collections.sort(Unknown Source)
	at xdman.ui.components.DownloadTableModel.sort(DownloadTableModel.java:68)
	at xdman.ui.components.DownloadTableModel.listChanged(DownloadTableModel.java:50)
	at xdman.ui.components.DownloadListView.refresh(DownloadListView.java:71)
	at xdman.ui.components.MainWindow.filter(MainWindow.java:374)
	at xdman.ui.components.MainWindow.initWindow(MainWindow.java:957)
	at xdman.ui.components.MainWindow.<init>(MainWindow.java:102)
	at xdman.XDMApp.showMainWindow(XDMApp.java:206)
	at xdman.XDMApp$1.run(XDMApp.java:112)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
checking for app update
[ Thread-3 ] manifest download response: 200
7.2.11 7.2.11
New session

```

after troubleshooting this issue I found a solution
just open terminal and remove the XDMan download list file

`rm ~/.xdman/downloads.txt`
this will remove the download list (which is the cause of the problem) and then the UI will be back

**Comment by joshjavier** [comment]
I'm also experiencing this issue on Pop!_OS 20.04. I tried @mohamed-khadragy's solution from https://github.com/subhra74/xdm/issues/492#issuecomment-803296056 and it works.

> `rm ~/.xdman/downloads.txt`
> this will remove the download list (which is the cause of the problem) and then the UI will be back

Since @mohamed-khadragy mentioned it might be a Java problem, here's my java version (if it helps):

```sh
~ ❯ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

p.s. sorry for creating a new issue, I'm still not very familiar with GitHub's UI :sweat_smile:

**Comment by Xan-Kerem** [comment]
Folks I solved this problem by removing /home/(your username)/.xdman/downloads.txt file.

**Comment by agungelfatih** [comment]
I didn't found the downloads.txt file but I solve this by remove the ~/.xdman/queues.txt  file
