### ISSUE TITLE
Downloads are forwarded to https://127.0.0.1:9614/204 in Firefox

### ISSUE THREAD

**Issue by VickySoni81** [subhra74/xdm#509]
**Bug Details**
When clicked on download links in Firefox Browser (version : 86.0-2) opens https://127.0.0.1:9614/204 which is a non-responsive page saying, It is occurring on both Windows and Linux on Firefox browser and the dialog box of xdm doesn't appear. But it is still working in other browser like Brave browser but not on Firefox. I have checked both extension version 2.2 and 2.1.

**Expected behavior**
Dialog box for download now should appear and Download video dialog should appear.

 - OS: Both Linux and Windows
 - Browser: Firefox v.86.0-2
 - XDM addon Version: 2.1 and 2,2
 - XDM Version: 7.2.8

**Generated log**
```
[ Thread-1 ] manifest download response: 204
Stat: 1
checking for app update
New session
[ Thread-1 ] manifest download response: 200
7.2.10 7.2.8
New session
[ Thread-5 ] java.io.IOException: Invalid request: üð­@Õ
                                                        ø£0ÁÌLÈÒù> J÷Æ£æ]sº?<üøÁníï)±èZfÆsEv ²@»CCÂ¾¶wåÒhW1Âªj0Ä7|}ó$À+À/Ì©Ì¨À,À0À
	at xdman.monitoring.Request.read(Request.java:23)
	at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.java:499)
	at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:528)
	at java.lang.Thread.run(Thread.java:748)
New session
[ Thread-7 ] java.io.IOException: Invalid request: üó.xì�D¯ûåºÜÊæûÖi®©-
                                                                      ­Aûì¶'¿g$À+À/Ì©Ì¨À,À0À
	at xdman.monitoring.Request.read(Request.java:23)
	at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.java:499)
	at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:528)
	at java.lang.Thread.run(Thread.java:748)
New session
[ Thread-8 ] java.io.IOException: Unexpected EOF while reading header line
	at xdman.util.NetUtils.readLine(NetUtils.java:18)
	at xdman.network.http.HeaderCollection.loadFromStream(HeaderCollection.java:91)
	at xdman.monitoring.Request.read(Request.java:28)
	at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.java:499)
	at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:528)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by subhra74** [comment]
Please use latest XDM version 7.2.11

**Comment by VickySoni81** [comment]
Thanks for the reply, just updated it its still doing the same thing. I figured it is due to some settings I did in the about:config file but can't figure out the exact setting causing the problem, as its working fine in a new profile.
