### ISSUE TITLE
Failed to append/convert file parts

### ISSUE THREAD

**Issue by garyhuge05** [subhra74/xdm#546]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
HELLO
I'm downloading a matlab file(that's 20.5G), wheras it keeps telling me "Failed to append/convert file parts, please check if the drive is full or write protected". My disk has 174G free space  and i think that's pretty enough. Below is the log.
download: 217619
[ AWT-EventQueue-0 ] File opened 65a8c476-4457-42fd-bd82-2076aa8327b1
[ AWT-EventQueue-0 ] id: 65a8c476-4457-42fd-bd82-2076aa8327b1
length: 3539978
offset: 2880172379
download: 3539978
[ AWT-EventQueue-0 ] File opened 1e2ce4e4-160a-41e6-8b99-63cd49ff9e68
[ AWT-EventQueue-0 ] id: 1e2ce4e4-160a-41e6-8b99-63cd49ff9e68
length: 19949856
offset: 2883712357
download: 19949856
[ AWT-EventQueue-0 ] File opened 8da3c18a-3e2c-4a42-9f3a-11f7f45f8c9a
[ AWT-EventQueue-0 ] id: 8da3c18a-3e2c-4a42-9f3a-11f7f45f8c9a
length: 27217440
offset: 2903662213
download: 27217440
[ AWT-EventQueue-0 ] File opened d625325a-a85a-4ff5-84ca-ab14ff8d8c13
[ AWT-EventQueue-0 ] id: d625325a-a85a-4ff5-84ca-ab14ff8d8c13
length: 383061
offset: 2930879653
download: 383061
[ AWT-EventQueue-0 ] File opened ba40fe5a-2fa6-49e3-a26d-f0b12bf112a4
[ AWT-EventQueue-0 ] id: ba40fe5a-2fa6-49e3-a26d-f0b12bf112a4
length: 1829002
offset: 2931262714
download: 1829002
[ AWT-EventQueue-0 ] File opened 807772fc-7934-41bc-9f2e-c642fc9b7760
[ AWT-EventQueue-0 ] id: 807772fc-7934-41bc-9f2e-c642fc9b7760
length: 3919343
offset: 2933091716
download: 3919343
[ AWT-EventQueue-0 ] File opened c0631465-94ef-4e45-9a6e-322991b5228f
[ AWT-EventQueue-0 ] id: c0631465-94ef-4e45-9a6e-322991b5228f
length: 8066446
offset: 2937011059
download: 8066446
[ AWT-EventQueue-0 ] File opened a55b980e-ae5e-4955-8631-b46b3e3b8177
[ AWT-EventQueue-0 ] id: a55b980e-ae5e-4955-8631-b46b3e3b8177
length: 23880453
offset: 2945077505
download: 23880453
[ AWT-EventQueue-0 ] File opened 7e48997c-2586-45cc-9a98-e910abc7f4fb
[ AWT-EventQueue-0 ] id: 7e48997c-2586-45cc-9a98-e910abc7f4fb
length: 697534
offset: 2968957958
download: 697534
[ AWT-EventQueue-0 ] File opened 2b1e26e4-aafa-4b66-886f-336d8dd1be9d
[ AWT-EventQueue-0 ] id: 2b1e26e4-aafa-4b66-886f-336d8dd1be9d
length: 2018487
offset: 2969655492
download: 2018487
[ AWT-EventQueue-0 ] File opened 30442e06-a01f-434e-813f-c628e46d51d1
[ AWT-EventQueue-0 ] id: 30442e06-a01f-434e-813f-c628e46d51d1
length: 4301234
offset: 2971673979
download: 4301234
[ AWT-EventQueue-0 ] File opened 4f2b2c7a-9c15-4b13-a5ca-a20a46619b24
[ AWT-EventQueue-0 ] id: 4f2b2c7a-9c15-4b13-a5ca-a20a46619b24
length: 8916385
offset: 2975975213
download: 8916385
[ AWT-EventQueue-0 ] File opened ad3172ff-3e51-4f71-8d85-15081b78f838
[ AWT-EventQueue-0 ] id: ad3172ff-3e51-4f71-8d85-15081b78f838
length: 163104090
offset: 2984891598
download: 163104090
[ AWT-EventQueue-0 ] File opened b5f23852-ddc5-4628-8ef0-137698fa2a50
[ AWT-EventQueue-0 ] id: b5f23852-ddc5-4628-8ef0-137698fa2a50
length: 328259058
offset: 3147995688
download: 328259058
[ AWT-EventQueue-0 ] File opened d21651c7-9ed0-4872-b717-cfe1a83277c5
[ AWT-EventQueue-0 ] id: d21651c7-9ed0-4872-b717-cfe1a83277c5
length: 668910173
offset: 3476254746
download: 668910173
[ AWT-EventQueue-0 ] File opened a73d15ee-cedd-4a98-863f-9f84f2cf0268
[ AWT-EventQueue-0 ] id: a73d15ee-cedd-4a98-863f-9f84f2cf0268
length: 1347939607
offset: 4145164919
download: 1347939607
[ AWT-EventQueue-0 ] File opened 7ba24800-9730-4c7f-8913-0c50e2b7c94d
[ AWT-EventQueue-0 ] id: 7ba24800-9730-4c7f-8913-0c50e2b7c94d
length: 720929132
offset: 5493104526
download: 720929132
[ AWT-EventQueue-0 ] File opened 4700b3cf-24ff-4092-806f-22f868972b5b
[ AWT-EventQueue-0 ] id: 4700b3cf-24ff-4092-806f-22f868972b5b
length: 665972236
offset: 6214033658
download: 665972236
[ AWT-EventQueue-0 ] File opened 829e75a3-4bef-45c2-9ec8-41d966ebb3de
[ AWT-EventQueue-0 ] id: 829e75a3-4bef-45c2-9ec8-41d966ebb3de
length: 1358941331
offset: 6880005894
download: 1358941331
[ AWT-EventQueue-0 ] File opened 979e3b07-ff64-4050-b0ed-a5711a25b120
[ AWT-EventQueue-0 ] id: 979e3b07-ff64-4050-b0ed-a5711a25b120
length: 1378418249
offset: 8238947225
download: 1378418249
[ AWT-EventQueue-0 ] File opened bffffa57-766e-440d-b1a0-423a24e35880
[ AWT-EventQueue-0 ] id: bffffa57-766e-440d-b1a0-423a24e35880
length: 1367274493
offset: 9617365474
download: 1367274493
[ AWT-EventQueue-0 ] File opened 9e93efc2-aaa3-4935-8ec8-060502da18b3
[ AWT-EventQueue-0 ] id: 9e93efc2-aaa3-4935-8ec8-060502da18b3
length: 871540216
offset: 10984639967
download: 871540216
[ AWT-EventQueue-0 ] File opened 500411a9-7f7f-4262-b118-1387655b1c11
[ AWT-EventQueue-0 ] id: 500411a9-7f7f-4262-b118-1387655b1c11
length: 23958561
offset: 11856180183
download: 23958561
[ AWT-EventQueue-0 ] File opened 9821f583-afcb-433a-94d8-4b3f50108dfe
[ AWT-EventQueue-0 ] id: 9821f583-afcb-433a-94d8-4b3f50108dfe
length: 23094664
offset: 11880138744
download: 23094664
[ AWT-EventQueue-0 ] File opened 292b269f-7679-4d9b-a18a-aca7bd7d048e
[ AWT-EventQueue-0 ] id: 292b269f-7679-4d9b-a18a-aca7bd7d048e
length: 470400236
offset: 11903233408
download: 470400236
[ AWT-EventQueue-0 ] File opened f363aa98-617c-4237-b46b-779e97ad9de4
[ AWT-EventQueue-0 ] id: f363aa98-617c-4237-b46b-779e97ad9de4
length: 57151886
offset: 12373633644
download: 57151886
[ AWT-EventQueue-0 ] File opened 95e7acac-91d2-4c73-8e5f-fcaec21ffc69
[ AWT-EventQueue-0 ] id: 95e7acac-91d2-4c73-8e5f-fcaec21ffc69
length: 493053
offset: 12430785530
download: 493053
[ AWT-EventQueue-0 ] File opened 37cae1bf-d775-4d42-8ae5-005ed63b64f9
[ AWT-EventQueue-0 ] id: 37cae1bf-d775-4d42-8ae5-005ed63b64f9
length: 2190607
offset: 12431278583
download: 2190607
[ AWT-EventQueue-0 ] File opened 424cdcb9-8ce2-449f-ab85-08cff371a8f8
[ AWT-EventQueue-0 ] id: 424cdcb9-8ce2-449f-ab85-08cff371a8f8
length: 4689273
offset: 12433469190
download: 4689273
[ AWT-EventQueue-0 ] File opened 43a9e1b1-5b1c-4e2b-92a7-2b3509406d80
[ AWT-EventQueue-0 ] id: 43a9e1b1-5b1c-4e2b-92a7-2b3509406d80
length: 9666167
offset: 12438158463
download: 9666167
[ AWT-EventQueue-0 ] File opened ef25f91f-2c3d-4c57-9ee3-00923b23101b
[ AWT-EventQueue-0 ] id: ef25f91f-2c3d-4c57-9ee3-00923b23101b
length: 40044931
offset: 12447824630
download: 40044931
[ AWT-EventQueue-0 ] File opened add40749-b015-4955-a76e-6046a0108841
[ AWT-EventQueue-0 ] id: add40749-b015-4955-a76e-6046a0108841
length: 80903082
offset: 12487869561
download: 80903082
[ AWT-EventQueue-0 ] File opened 9ea7be63-20c6-4099-b939-22392ba417e1
[ AWT-EventQueue-0 ] id: 9ea7be63-20c6-4099-b939-22392ba417e1
length: 162302563
offset: 12568772643
download: 162302563
[ AWT-EventQueue-0 ] File opened 33c1c8c7-db1b-4752-b811-03c6ffc792ef
[ AWT-EventQueue-0 ] id: 33c1c8c7-db1b-4752-b811-03c6ffc792ef
length: 329280047
offset: 12731075206
download: 329280047
[ AWT-EventQueue-0 ] File opened 28db9666-4291-40ea-ae71-0287dc6d1864
[ AWT-EventQueue-0 ] id: 28db9666-4291-40ea-ae71-0287dc6d1864
length: 670469313
offset: 13060355253
download: 670469313
[ AWT-EventQueue-0 ] File opened ec0c124c-a522-4f0a-96f3-421b38731716
[ AWT-EventQueue-0 ] id: ec0c124c-a522-4f0a-96f3-421b38731716
length: 598477148
offset: 13730824566
download: 598477148
[ AWT-EventQueue-0 ] File opened 64b5b415-27c4-4560-aca1-60b048c4c8d4
[ AWT-EventQueue-0 ] id: 64b5b415-27c4-4560-aca1-60b048c4c8d4
length: 171545028
offset: 14329301714
download: 171545028
[ AWT-EventQueue-0 ] File opened 46e6be27-b072-4b3f-9a81-55439ac3e018
[ AWT-EventQueue-0 ] id: 46e6be27-b072-4b3f-9a81-55439ac3e018
length: 620656554
offset: 14500846742
download: 620656554
[ AWT-EventQueue-0 ] File opened 85b29e62-e61b-4932-aad9-ad954f1fb13f
[ AWT-EventQueue-0 ] id: 85b29e62-e61b-4932-aad9-ad954f1fb13f
length: 1355456655
offset: 15121503296
download: 1355456655
[ AWT-EventQueue-0 ] File opened acffa623-f0d8-4f0a-af0b-b9400345843c
[ AWT-EventQueue-0 ] id: acffa623-f0d8-4f0a-af0b-b9400345843c
length: 2746386079
offset: 16476959951
download: 2746386079
[ AWT-EventQueue-0 ] File opened c5a3be4d-a6dd-43a4-a9da-37d0873b1d13
[ AWT-EventQueue-0 ] id: c5a3be4d-a6dd-43a4-a9da-37d0873b1d13
length: 702199693
offset: 19223346030
download: 702199693
[ AWT-EventQueue-0 ] File opened 173595ef-abc7-487f-be5c-3614f1a55617
[ AWT-EventQueue-0 ] id: 173595ef-abc7-487f-be5c-3614f1a55617
length: 676403377
offset: 19925545723
download: 676403377
[ AWT-EventQueue-0 ] File opened d9be125a-e6eb-4219-acc5-5eee2b4d278d
[ AWT-EventQueue-0 ] id: d9be125a-e6eb-4219-acc5-5eee2b4d278d
length: 1367330834
offset: 20601949100
download: 1367330834
[ AWT-EventQueue-0 ] Restore success
[ AWT-EventQueue-0 ] List changed
[ Thread-3 ] checking for same named file on disk...
[ Thread-3 ] Updating file name- old: _igetintopc.com_MathWorks_MATLAB_R2019_x64
.rar new: _igetintopc.com_MathWorks_MATLAB_R2019_x64.rar
[ Thread-3 ] assembling...
[ Thread-3 ] chunk 0 false
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-2 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-3 ] List updated
[ Thread-3 ] List updated
New session
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-4 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-3 ] List updated
[ Thread-3 ] List updated
New session
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-5 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.j
ava:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-3 ] List updated
[ Thread-3 ] List updated
New session
[ Thread-3 ] List updated
[ Thread-3 ] List updated
[ Thread-3 ] java.io.IOException: 磁盘空间不足。
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(Unknown Source)
        at xdman.downloaders.SegmentDownloader.assemble(SegmentDownloader.java:3
39)
        at xdman.downloaders.SegmentDownloader$1.run(SegmentDownloader.java:598)

        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-3 ] java.io.IOException: java.io.IOException: 磁盘空间不足。
        at xdman.downloaders.SegmentDownloader.assemble(SegmentDownloader.java:3
96)
        at xdman.downloaders.SegmentDownloader$1.run(SegmentDownloader.java:598)

        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 磁盘空间不足。
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(Unknown Source)
        at xdman.downloaders.SegmentDownloader.assemble(SegmentDownloader.java:3
39)
        ... 2 more
[ Thread-3 ] List updated
[ Thread-3 ] removed

The chinese "磁盘空间不足” means insufficient disk space, which i can't understand why. Thanks.

**Comment by garyhuge05** [comment]
oh god i know why, thanks anyway
