### ISSUE TITLE
XDM won't install properly

### ISSUE THREAD

**Issue by A4000Bear** [subhra74/xdm#592]
## Checklist

- [ X] I'm asking a question
- [ X] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I'm using Linux Debian 10,  Firefox 78.11.0esr, Cinnamon desktop. First time user here.
Downloaded and unpacked xdm-setup-7.2.11 successfully. 
Got no response when clicking on the 'Xtreme Download Manager' icon in the menu.
Clicking on that icon a second time gives a popup message "An older version of XDM is already running"
There appears to be no way to get into the main GUI.
Tried running xdman from the terminal and got this:

david@Debian:/opt/xdman$ xdman
[ main ] loading...
[ main ] 11.0.6 4.19.0-17-amd64
[ main ] Loading config...
[ main ] Creating folders
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
en
[ main ] Loading language en
[ main ] Context initialized
[ Thread-4 ] java.net.BindException: Address already in use (Bind failed)
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at xdman.monitoring.BrowserMonitor.run(BrowserMonitor.java:186)
	at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-4 ] instance already runninng
checking for app update
[ Thread-3 ] manifest download response: 200
7.2.11 7.2.11

The older version popup message appeared  again. I could find no way to exit or stop, so I rebooted and ran from the terminal again, but got exactly the same response.

I had tried removing and reinstalling, but that did not help.

I have never had a previous older version installed. 
Any suggestions?

**Comment by A4000Bear** [comment]
Problem solved by wiping my boot partition and reinstalling everything. Might seem extreme, but once I find myself spending more than about 2 hours on a problem like this, I find it quicker and easier to go 'nuclear' and start again.
