### ISSUE TITLE
XDMan no longer works

### ISSUE THREAD

**Issue by Lehmeiers** [subhra74/xdm#618]
I have the problem that XDMAN no longer works under Manjaro, because the Java version has been upgraded from 15 to 16.
When is a new version coming?

My System:

inxi -Fxxxzo System: Kernel: 5.4.134-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 Desktop: Xfce 4.16.0 tk: Gtk 3.24.29 info: xfce4-panel wm: xfwm 4.16.1 vt: 7 dm: LightDM 1.30.0 Distro: Manjaro Linux base: Arch Linux Machine: Type: Desktop System: Dell product: OptiPlex 360 v: N/A serial: <filter> Chassis: type: 6 serial: <filter> Mobo: Dell model: 0T656F v: A01 serial: <filter> BIOS: Dell v: A07 date: 06/18/2012 CPU: Info: Dual Core model: Pentium E5200 bits: 64 type: MCP arch: Penryn rev: 6 cache: L2: 2 MiB flags: lm nx pae sse sse2 sse3 ssse3 bogomips: 9978 Speed: 2427 MHz min/max: N/A Core speeds (MHz): 1: 2427 2: 2209 Graphics: Device-1: NVIDIA GT218 [GeForce 210] driver: nouveau v: kernel bus-ID: 01:00.0 chip-ID: 10de:0a65 class-ID: 0300 Device-2: Microsoft LifeCam HD-5000 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 2-1:2 chip-ID: 045e:076d class-ID: 0102 Display: x11 server: X.Org 1.20.11 compositor: xfwm4 v: 4.16.1 driver: loaded: nouveau unloaded: modesetting alternate: fbdev,nv,vesa resolution: 1680x1050~60Hz s-dpi: 96 OpenGL: renderer: NVA8 v: 3.3 Mesa 21.1.5 direct render: Yes Audio: Device-1: Intel NM10/ICH7 Family High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel bus-ID: 00:1b.0 chip-ID: 8086:27d8 class-ID: 0403 Device-2: NVIDIA High Definition Audio driver: snd_hda_intel v: kernel bus-ID: 01:00.1 chip-ID: 10de:0be3 class-ID: 0403 Device-3: Microsoft LifeCam HD-5000 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 2-1:2 chip-ID: 045e:076d class-ID: 0102 Sound Server-1: ALSA v: k5.4.134-1-MANJARO running: yes Sound Server-2: JACK v: 0.125.0 running: no Sound Server-3: PulseAudio v: 14.2 running: no Sound Server-4: PipeWire v: 0.3.32 running: yes Network: Device-1: Broadcom NetLink BCM5784M Gigabit Ethernet PCIe vendor: Dell driver: tg3 v: 3.137 port: dc80 bus-ID: 02:00.0 chip-ID: 14e4:1698 class-ID: 0200 IF: enp2s0 state: down mac: <filter> Device-2: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter driver: 8139too v: 0.9.28 port: cc00 bus-ID: 03:00.0 chip-ID: 10ec:8139 class-ID: 0200 IF: enp3s0 state: unknown speed: 100 Mbps duplex: full mac: <filter> Drives: Local Storage: total: 931.51 GiB used: 555.75 GiB (59.7%) ID-1: /dev/sda vendor: Samsung model: SSD 860 QVO 1TB size: 931.51 GiB speed: <unknown> type: SSD serial: <filter> rev: 2B6Q scheme: GPT Partition: ID-1: / size: 105.18 GiB used: 63.05 GiB (59.9%) fs: ext4 dev: /dev/sda2 ID-2: /boot size: 973.4 MiB used: 149 MiB (15.3%) fs: ext4 dev: /dev/sda1 ID-3: /home size: 779.45 GiB used: 492.42 GiB (63.2%) fs: ext4 dev: /dev/sda3 Swap: ID-1: swap-1 type: partition size: 30.12 GiB used: 133.8 MiB (0.4%) priority: -2 dev: /dev/sda4 Unmounted: Message: No unmounted partitions found. Sensors: System Temperatures: cpu: 51.0 C mobo: N/A gpu: nouveau temp: 49.0 C Fan Speeds (RPM): N/A Info: Processes: 166 Uptime: 4h 52m wakeups: 0 Memory: 3.78 GiB used: 2.74 GiB (72.4%) Init: systemd v: 248 Compilers: gcc: 11.1.0 clang: 12.0.1 Packages: note: see --pkg pacman: 1842 Shell: Bash v: 5.1.8 running-in: xfce4-terminal inxi: 3.3.06

Sincerely R.Lehmeier

**Comment by madmangr** [comment]
Not working on Arch.  

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: xdman/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

**Comment by Lehmeiers** [comment]
What I have found so far indicates that XDMAN cannot cope with the current Java version (16.u8-1) in Manjaro.
Apparently, adjustments have to be made here.

We'll see if that still happens.
It would be great if it would work again.

**Comment by subhra74** [comment]
The error message posted above indicates even newer version of java runtime is required. Does the generic installed for linux not work?

**Comment by Lehmeiers** [comment]
But XDMAN works again, although I don't know why. I have to start it manually but at least it works.

Otherwise I always let it start automatically and when I wanted to download something with Firefox, the client could access it right away.

Unfortunately, it doesn't work under Manjaro anymore. 
I have entered the following under "Settings => Settings => Session and startup behaviour => Automatically started applications => xdman ( Downloadmanager =>Command" "/usr/lib/jvm/default/bin/java" -Xmx1024m -jar "/opt/xdman/xdman.jar" - unfortunately without success.

Translated with www.DeepL.com/Translator (free version)

**Comment by zakariamanssouri** [comment]
the error is occured because you have an incompatible java version  
![image](https://user-images.githubusercontent.com/80859231/184723495-4746158f-7424-4da7-bb2e-d3601c08804e.png)
you have to set the java version to 11 or later with the command 
![image](https://user-images.githubusercontent.com/80859231/184723659-e7fc47a0-ec44-4f0d-bbc3-c6d3a3d4b2af.png)
and run it with : 
![image](https://user-images.githubusercontent.com/80859231/184723729-91991241-4199-4768-a5ad-49b151b176ca.png)
