### ISSUE TITLE
Setting proxy in proxy settings doesn't work and disappears

### ISSUE THREAD

**Issue by denishem** [subhra74/xdm#672]
**Describe the bug**
Proxy settings in GUI disappear.

**To Reproduce**
1. Go to settings
2. Click on "Network Settings"
3. Scroll to "Proxy Settings"
4. Check "Use proxy server"
5. Enter proxy information
6. Go back
7. Go to "Network Settings" Again
8. Proxy information is gone

**Expected behavior**
Proxy settings don't disappear and are used.

**Screenshots**
![Peek 12-10-2021 10-57](https://user-images.githubusercontent.com/48387052/136925424-487781dc-b956-4742-ba5e-9a22b04ea999.gif)

**please complete the following information:**
 - OS: EndeavourOS (Arch Linux)
 - XDM Version 7.2.11

**Generated log using below method**
 ```
 [ main ] loading...
[ main ] 11.0.6 5.14.11-arch1-1
[ main ] Loading config...
[ main ] Creating folders
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
en
[ main ] Loading language en
[ main ] Context initialized
[ Thread-4 ] java.net.BindException: Adresse déjà utilisée (Bind failed)
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at xdman.monitoring.BrowserMonitor.run(BrowserMonitor.java:186)
	at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-4 ] instance already runninng
```

**Comment by inoshy** [comment]
This project is not actively mainained anymore.
