### ISSUE TITLE
OneDrive does not work 90% of the time

### ISSUE THREAD

**Issue by seyo-IV** [subhra74/xdm#937]
**Describe the bug**
Download window does not pop whe ndownloaded trough OneDrive.
**To Reproduce**
1. Go to Browser
2. Click on download
4. See, nothing happened 

**Expected behavior**
Download window pops before he xdm window

**please complete the following information:**
 - OS: Win 11
 - Browser Firefox
 - XDM addon Version 2.2
 - XDM Version LAtest Release
 
**Generated log using below method**

C:\Program Files (x86)\XDM>"java-runtime\bin\java" -jar xdman.jar
[ main ] loading...
[ main ] 11.0.6 10.0
[ main ] Loading config...
[ main ] Creating folders
Zoom index; 5 1.5
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
en
[ main ] Loading language en
[ main ] Context initialized
[ Thread-1 ] java.net.BindException: Address already in use: NET_Bind
        at java.base/java.net.PlainSocketImpl.bind0(Native Method)
        at java.base/java.net.PlainSocketImpl.socketBind(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.bind(Unknown Source)
        at java.base/java.net.ServerSocket.bind(Unknown Source)
        at java.base/java.net.ServerSocket.bind(Unknown Source)
        at xdman.monitoring.BrowserMonitor.run(BrowserMonitor.java:186)
        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-1 ] instance already runninng

**Comment by seyo-IV** [comment]
Also probably important. Im downloading a BIN fiole and i have added BIN to the list.
